name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone Bot-store repository
      run: |
        git clone https://github.com/DittKanaeru/Bot-store.git

    # Step 2: Navigate into the LilyWa directory
    - name: Change directory to Bot-store
      run: cd Bot-store

    # Step 3: Unzip lilybot.zip file inside the LilyWa folder
    - name: Unzip Bot-WhatsApp-Store-main.rar
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip Bot-store/Bot-WhatsApp-Store-main.rar -d ./Bot-store # Unzip Bot-WhatsApp-Store-main.rar in the Bot-store directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd Bot-store
        npm install

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd Bot-store
        npm start
